#This Libraries helps to remove all the unnecessary warning generated by the interpreter or other libraries
#This warnings are not much important and doesn't effect our final code but reduce the readibility experience of output
import os
import platform
import sys
import warnings
import logging
from sklearn.exceptions import ConvergenceWarning

#For silencing TensorFlow and System Warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
logging.getLogger('tensorflow').setLevel(logging.ERROR)
warnings.filterwarnings("ignore", category=ConvergenceWarning)

#Standard Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Machine Learning Libraries
#Tensorflow
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#Scikit-Learn 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.impute import KNNImputer

#Setting a fixed SEED to control huge adverse randomity of data analysis
#Though the output still depends on the Device, OS and libraries thus generates random output everytime we run
RANDOM_SEED = 123
np.random.seed(RANDOM_SEED)
tf.random.set_seed(RANDOM_SEED)

#Defining Columns
X_COL = "sepal_length"
TARGETS = ["sepal_width", "petal_length", "petal_width"]
all_cols = [X_COL] + TARGETS

#Importing the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
cols = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

print("Note : Close each graph window as it appears to continue")
sys.stdout.flush()

try:
    df = pd.read_csv(url, header=None, usecols=[0, 1, 2, 3], names=cols)
except Exception:
    print("Internet download failed. Looking for 'iris.data' locally...")
    try:
        df = pd.read_csv("iris.data", header=None, usecols=[0, 1, 2, 3], names=cols)
    except FileNotFoundError:
        print("Error: Could not find 'iris.data' on your computer or the internet.")
        sys.exit(1)

#Missing Data Mechanisms

#MCAR -> Missing Completely At Random
def induce_mcar(df, missing_rate, targets=TARGETS, seed=RANDOM_SEED):
    rng = np.random.RandomState(seed)
    data = df.copy()
    for col in targets:
        mask = rng.rand(len(data)) < missing_rate
        data.loc[mask, col] = np.nan
    return data

#MAR -> Missing At Random
def induce_mar(df, missing_rate, targets=TARGETS, pivot_col="sepal_length", seed=RANDOM_SEED):
    rng = np.random.RandomState(seed)
    data = df.copy()
    median = data[pivot_col].median()

    condition_mask = data[pivot_col] > median
    condition_proportion = condition_mask.mean()
    if condition_proportion > 0:
        prob_given_condition = missing_rate / condition_proportion
    else:
        prob_given_condition = 0
    if prob_given_condition > 1.0:
        prob_given_condition = 1.0
    for col in targets:
        rand_mask = rng.rand(len(data)) < prob_given_condition
        mask = condition_mask & rand_mask
        data.loc[mask, col] = np.nan
    return data

#MNAR -> Missing Not At Random
def induce_mnar(df, missing_rate, targets=TARGETS, seed=RANDOM_SEED):
    rng = np.random.RandomState(seed)
    data = df.copy()
    for col in targets:
        median = data[col].median()
        condition_mask = data[col] > median
        condition_proportion = condition_mask.mean()
        if condition_proportion == 0:
            continue
        prob_given_condition = missing_rate / condition_proportion
        if prob_given_condition > 1.0:
            prob_given_condition = 1.0
        rand_mask = rng.rand(len(data)) < prob_given_condition
        mask = condition_mask & rand_mask
        data.loc[mask, col] = np.nan
    return data

#Building Our ANN model for prediction
def build_ann(input_dim=1, hidden_units=16, seed=RANDOM_SEED):
    tf.random.set_seed(seed)
    model = Sequential([
        tf.keras.layers.Input(shape=(input_dim,)),
        Dense(hidden_units, activation="relu"),
        Dense(hidden_units, activation="relu"),
        Dense(len(TARGETS))
    ])
    model.compile(optimizer="adam", loss="mse")
    return model

#Iterative Imputer with ANN
def iterative_ann_imputer(train_miss_data, train_truth_df, missing_mask, max_iter=20, verbose=False):
    df = train_miss_data.copy()
    scaler = StandardScaler()
    df[X_COL] = df[X_COL].astype(float)
    missing_row_idx = train_miss_data[TARGETS].isna().any(axis=1)
    if not missing_row_idx.any():
        return [0] * max_iter
    true_values = train_truth_df[TARGETS].values[missing_mask.values]
    mse_history = []
    for t in TARGETS:
        mean_val = df[t].mean(skipna=True)
        df[t] = df[t].fillna(mean_val)
    for iteration in range(max_iter):
        X_scaled = scaler.fit_transform(df[[X_COL]])
        y = df[TARGETS].values
        model = build_ann(input_dim=1, hidden_units=16)
        model.fit(X_scaled, y, epochs=200, verbose=0)
        X_miss_scaled = scaler.transform(train_miss_data.loc[missing_row_idx, [X_COL]])
        preds = model.predict(X_miss_scaled, verbose=0)
        df.loc[missing_row_idx, TARGETS] = preds
        imputed_values = df[TARGETS].values[missing_mask.values]
        current_mse = mean_squared_error(true_values, imputed_values)
        mse_history.append(current_mse)
        if verbose:
            print(f"Iteration {iteration + 1}/{max_iter} completed.")
    return mse_history

mechanisms = ["MCAR", "MAR", "MNAR"]
missing_rates = [0.30, 0.50, 0.70]
results = []
iteration_axis = list(range(1, 21))

train_df = df.copy()

for mech in mechanisms:
    for mr in missing_rates:
        if mech == "MCAR":
            train_miss_data = induce_mcar(train_df, mr, seed=RANDOM_SEED)
        elif mech == "MAR":
            train_miss_data = induce_mar(train_df, mr, pivot_col="sepal_length", seed=RANDOM_SEED)
        elif mech == "MNAR":
            train_miss_data = induce_mnar(train_df, mr, seed=RANDOM_SEED)

        missing_mask = train_miss_data[TARGETS].isna()

        ann_mse_history = iterative_ann_imputer(train_miss_data, train_df, missing_mask, max_iter=20)
        mse_ann = ann_mse_history[-1]
        results.append({
            "Mechanism": mech,
            "Missing%": int(mr * 100),
            "Method": "ANN",
            "MSE": mse_ann
        })

        plt.figure(figsize=(10, 6))
        plt.plot(iteration_axis, ann_mse_history, marker='o', linestyle='--')
        plt.title(f"Iterative ANN Imputation MSE vs. Iteration ({mech} - {int(mr * 100)}%)", fontsize=16)
        plt.xlabel("Iteration Number", fontsize=12)
        plt.ylabel("Imputation MSE", fontsize=12)
        plt.xticks(iteration_axis)
        plt.grid(True)
        plt.show()

        knn_imputer = KNNImputer(n_neighbors=5)
        df_knn_imputed = pd.DataFrame(knn_imputer.fit_transform(train_miss_data[all_cols]), columns=all_cols)
        true_values = train_df[TARGETS].values[missing_mask.values]
        imputed_values = df_knn_imputed[TARGETS].values[missing_mask.values]
        mse_knn = mean_squared_error(true_values, imputed_values)
        results.append({
            "Mechanism": mech,
            "Missing%": int(mr * 100),
            "Method": "KNN",
            "MSE": mse_knn
        })

summary_df = pd.DataFrame(results)
summary_df = summary_df[["Mechanism", "Missing%", "Method", "MSE"]]
summary_df = summary_df.sort_values(["Mechanism", "Missing%", "Method"]).reset_index(drop=True)

#Main Output
print("Imputation Performance Comparison :-")
print(summary_df)
pivot = summary_df.pivot_table(index=["Mechanism", "Missing%"], columns="Method", values=["MSE"])
print("\nSummary:-")
print(pivot)